// Book Club, offline path (no window.claude): add book -> log -> questions (local stems) -> draw -> finish
import {open,shot,SPEECH_MOCK,overflow} from './lib.mjs';import {setup,draw,toastText} from './common.mjs';
const vp=process.argv[2]||'ipad';const P='bc-off-'+vp+'-';const out=[];const ok=(c,m)=>{out.push((c?'PASS ':'FAIL ')+m);if(!c)process.exitCode=1};
const p=await open(vp,{init:SPEECH_MOCK});await setup(p);
await shot(p,P+'01-home');
await p.click('[data-act="bookclub"]');await shot(p,P+'02-shelf-empty');ok(await overflow(p)<=0,'shelf no overflow');
await p.click('[data-act="bc-add"][data-s="0"]');await p.fill('#bCh','20');await p.click('[data-act="bc-color"][data-c="#27b884"]');await shot(p,P+'03-add');
ok(await p.inputValue('#bTitle')==='The City of Ember','suggested title prefilled');
await p.click('[data-act="bc-save-book"]');ok(await p.evaluate(()=>S.books.length===1&&S.books[0].chapters===20&&S.books[0].color==='#27b884'),'book saved with chapters+color');
await shot(p,P+'04-book');
await p.click('[data-act="bc-log"]');
await p.fill('#bcText','the girl found a old box in the storeroom.');await p.waitForTimeout(100);
ok(await p.evaluate(()=>document.querySelector('#gWho').classList.contains('met')&&!document.querySelector('#gWhy').classList.contains('met')),'who met, why not yet');
await p.click('[data-act="bc-send"]');await p.waitForTimeout(400);
ok(await p.evaluate(()=>S.books[0].log.length===1&&S.days[today()].book===true),'entry logged + day.book');
const fb=await p.evaluate(()=>document.querySelector('#bcCoach').innerText);ok(/Glow/.test(fb)&&/Grow/.test(fb)&&/WHY/i.test(fb),'local coach glow/grow about why: '+fb.replace(/\n/g,' | ').slice(0,160));
await shot(p,P+'05-log-feedback');
const h0=await p.evaluate(()=>S.hearts);
await p.fill('#bcText','The girl found an old box in the storeroom because the lights went out.');await p.click('[data-act="bc-send"]');await p.waitForTimeout(400);
ok(await p.evaluate(()=>S.books[0].log[0].rev===true&&/because/.test(S.books[0].log[0].summary)),'revision saved');ok(await p.evaluate(h=>S.hearts-h,h0)===3,'revision bonus +3');
await p.click('[data-act="bc-to-think"]');await shot(p,P+'06-think-intro');
await p.click('[data-act="bc-ask"]');await p.waitForTimeout(400);
const qs=await p.evaluate(()=>BC.think.qs);ok(qs.length===3,'3 questions');ok(qs[0].kind==='summary'&&qs[0].q.startsWith('You wrote: “The girl found an old box'),'first question grounded in her summary: '+qs[0].q);
ok(await p.evaluate(()=>BC.think.src)==='local','offline fallback path used');
const ta=await p.$$('.bc-ans');for(const [i,t] of ta.entries())await t.fill(['I think she was curious because it was dark.','She felt scared and excited.','Maybe she opens the box next.'][i]||'Yes');
if(await p.$('.bc-word'))await p.fill('.bc-word','storeroom');
await p.click('[data-act="bc-share"]');await p.waitForTimeout(300);
const reps=await p.evaluate(()=>BC.think.replies);ok(reps&&reps.length===3&&!reps.some(r=>/wrong/i.test(r)),'warm replies: '+reps.join(' / '));
ok(await p.evaluate(()=>S.books[0].log[0].qs.length===3),'answers saved to log');
await shot(p,P+'07-think-replies');
await p.click('[data-act="bc-to-make"]');await shot(p,P+'08-make-choose');
await p.click('[data-act="bc-make-kind"][data-k="draw"]');await p.click('[data-act="dr-color"][data-c="#e8483a"]');await p.click('[data-act="dr-size"][data-s="0.03"]');
await draw(p);await p.click('[data-act="dr-color"][data-c="#2b8cff"]');await draw(p);await p.click('[data-act="dr-undo"]');await shot(p,P+'09-draw');
await p.click('[data-act="dr-save"]');await p.waitForTimeout(300);const tt=await toastText(p);ok(/this device only/i.test(tt),'no-db gentle message: '+tt);
const st=await p.evaluate(()=>{const e=S.books[0].log[0];const u=localStorage.getItem('critter-cove-art-'+e.artId)||'';return{art:e.art,artId:e.artId,len:u.length,jpeg:u.startsWith('data:image/jpeg'),stateHasImg:JSON.stringify(S).includes('data:image')}});
ok(st.art&&st.jpeg&&st.len>1000&&st.len<80000,'drawing saved as JPEG in localStorage, '+st.len+' chars');ok(!st.stateHasImg,'no image data inside main state');
await p.waitForTimeout(300);await shot(p,P+'10-book-with-art');
await p.click('[data-act="bc-finish"]');await p.click('[data-act="bc-rate"][data-r="5"]');await p.fill('#bFav','The girl');await p.click('[data-act="bc-finish-go"]');await p.waitForTimeout(300);
ok(await p.evaluate(()=>statC('chapters')===1&&statC('bookart')===1&&statC('books')===1),'statC chapters/bookart/books = 1/1/1');
await shot(p,P+'11-certificate');ok(await overflow(p)<=0,'cert no overflow');
await p.click('[data-act="bc-home"]');await p.waitForTimeout(300);await shot(p,P+'12-shelf-gallery');
ok(await p.evaluate(()=>document.querySelectorAll('.bc-gitem img.ok').length===1),'gallery shows drawing');
await p.evaluate(()=>renderDash());await shot(p,P+'13-dash');
ok(await p.evaluate(()=>/Book Club reading log/.test(document.body.innerText)&&/storeroom/.test(document.querySelector('.rlog').innerText)),'dashboard reading log row');
ok(await p.evaluate(()=>readingLogText().includes('Chapter 1')),'copyable reading log text');
ok(p.errs.length===0,'no errors '+p.errs.join(' | '));console.log(out.join('\n'));await p.b.close();
