/* ---------- Critter Cove: field guide data, items, scenes ---------- */
const SPEC={
 fox:{sp:'Gray Fox',cap:'A real gray fox. Gray foxes live in Florida and across much of North America.',intro:['Gray foxes can climb trees, using their sharp, curved claws.','They are about the size of a small dog.','They mostly hunt at night and eat mice, insects and fruit.'],credit:'Photo: VJAnderson, CC BY-SA 4.0, Wikimedia Commons',quiz:[['What can gray foxes do that most foxes can’t?','Climb trees','Fly short distances','Breathe underwater'],['When do gray foxes usually hunt?','At night','Only at noon','Only in winter'],['About how big is a gray fox?','Like a small dog','Like a horse','Like a mouse']]},
 raccoon:{sp:'Raccoon',cap:'A real raccoon in a city park.',intro:['Raccoons have a dark “mask” around their eyes and rings on their tails.','Their front paws work almost like hands, and they feel for food in the water.','They eat almost anything: fruit, bugs, fish, and sometimes trash!','Raccoons are most active at night.'],credit:'Photo: Rhododendrites, CC BY-SA 4.0, Wikimedia Commons',quiz:[['What pattern do raccoons have around their eyes?','A dark mask','Pink spots','White stripes'],['How do raccoons find food in water?','They feel for it with their paws','They listen with their tails','They use a net'],['When are raccoons most active?','At night','At lunchtime','Only on rainy days']]},
 rabbit:{sp:'Marsh Rabbit',cap:'A real marsh rabbit at Sweetwater Wetlands Park in Gainesville, Florida.',intro:['Marsh rabbits live in Florida’s wet marshes and swamps.','Unlike most rabbits, they are good swimmers.','They often walk on their back legs instead of hopping.','They eat grasses and other plants.'],credit:'Photo: Peter Chen, CC BY 4.0, Wikimedia Commons',quiz:[['Where do marsh rabbits live?','Wet marshes and swamps','Dry deserts','Snowy mountains'],['What are marsh rabbits good at?','Swimming','Flying','Climbing tall trees'],['What do marsh rabbits eat?','Grasses and plants','Fish','Other rabbits']]},
 otter:{sp:'River Otter',cap:'A real river otter at a wildlife refuge.',intro:['River otters have thick fur that keeps them warm and dry in the water.','They can close their ears and nose when they dive.','They eat fish, crabs and crayfish.','Otters love to slide and play!'],credit:'Photo: U.S. Fish and Wildlife Service, public domain, Wikimedia Commons',quiz:[['What can otters close when they dive?','Their ears and nose','Their tails','Their feet'],['What do river otters eat?','Fish, crabs and crayfish','Leaves and bark','Seeds'],['What do otters love to do?','Slide and play','Sleep all year','Build nests in trees']]},
 owl:{sp:'Burrowing Owl',cap:'A real burrowing owl standing on a post.',intro:['Burrowing owls live in holes in the ground instead of in trees.','They are awake during the day, not just at night.','They are small, only about 9 inches tall.','They bob their heads up and down when they are curious.'],credit:'Photo: Charles J. Sharp, CC BY-SA 4.0, Wikimedia Commons',quiz:[['Where do burrowing owls live?','In holes in the ground','At the top of tall trees','In the ocean'],['When are burrowing owls awake?','During the day too','Never during the day','Only in winter'],['What do they do when they’re curious?','Bob their heads','Sing a song','Change color']]},
 panther:{sp:'Florida Panther',cap:'A real Florida panther in Everglades National Park.',intro:['The Florida panther is Florida’s official state animal.','It is a kind of cougar, also called a puma or mountain lion.','Florida panthers are endangered. Only about 120 to 230 adults live in the wild.','They mostly hunt deer and wild hogs.'],credit:'Photo: Rodney Cammauf, National Park Service, public domain, Wikimedia Commons',quiz:[['What is special about the Florida panther?','It’s Florida’s state animal','It can fly','It lives only in the ocean'],['What kind of cat is it?','A kind of cougar','A house cat','A tiger'],['What does endangered mean for panthers?','Very few are left','There are millions','They are all in zoos']]},
 deer:{sp:'Key Deer',cap:'A real Key deer on Big Pine Key, Florida.',intro:['Key deer live only in the Florida Keys.','They are the smallest deer in North America, about as tall as a big dog.','They can swim from island to island.','They are endangered, so drivers go slowly where they live.'],credit:'Photo: Joseph C. Boone, CC BY-SA 3.0, Wikimedia Commons',quiz:[['Where do Key deer live?','Only in the Florida Keys','All over the world','In Canada'],['How big are Key deer?','About as tall as a big dog','Taller than a giraffe','As small as a mouse'],['How do Key deer get between islands?','They swim','They fly','They ride boats']]},
 bear:{sp:'Florida Black Bear',cap:'A real Florida black bear, photographed by a wildlife camera set up by Florida biologists.',intro:['The Florida black bear is Florida’s biggest land mammal.','Even though they are bears, they eat mostly plants, like berries, nuts and acorns.','They have an amazing sense of smell.','Locking up trash keeps bears safe and wild.'],credit:'Photo: Florida Fish and Wildlife Conservation Commission, public domain, Wikimedia Commons',quiz:[['What do Florida black bears eat the most?','Plants, like berries and nuts','Only fish','Rocks'],['What sense is super strong in bears?','Smell','Taste','Nothing special'],['How can people help keep bears wild?','Lock up their trash','Feed them cookies','Leave food outside']]},
 turtle:{sp:'Loggerhead Sea Turtle',cap:'A real loggerhead sea turtle swimming overhead.',intro:['Loggerheads are named for their big, heavy heads and strong jaws.','They crunch crabs, clams and snails.','Mother turtles crawl onto Florida beaches at night to lay about 100 eggs.','Bright beach lights confuse baby turtles, so beach towns turn lights down at night.'],credit:'Photo: ukanda, CC BY 2.0, Wikimedia Commons',quiz:[['Why are they called loggerheads?','They have big, heavy heads','They live in logs','They eat logs'],['About how many eggs does a mother lay?','About 100','Just 1','A million'],['Why do beach towns turn lights down at night?','So baby turtles find the ocean','To save candy','So fish can sleep']]},
 gator:{sp:'American Alligator',cap:'A real American alligator resting on the ground.',intro:['The American alligator is Florida’s official state reptile.','Alligators have a wide, U-shaped snout. Crocodiles have a pointier, V-shaped snout.','Their eyes and nostrils are on top of their head, so they can hide in water and still see and breathe.','Baby alligators chirp to call their mom.'],credit:'Photo: Postdlf, CC BY-SA 3.0, Wikimedia Commons',quiz:[['What shape is an alligator’s snout?','Wide, like a U','Pointy, like a V','Square'],['Why are their eyes on top of their head?','To see while hiding in water','To look at the stars','So they can sleep'],['How do baby alligators call their mom?','They chirp','They bark','They clap']]},
 flamingo:{sp:'American Flamingo',cap:'A real American flamingo spotted at Clearwater Beach, Florida.',intro:['Flamingos get their pink color from the shrimp and algae they eat.','They often stand on one leg.','They eat with their heads upside down, filtering food out of the water with their beaks.','Wild flamingos are sometimes seen in Florida Bay and the Everglades.'],credit:'Photo: JeffreyGammon, CC BY 4.0, Wikimedia Commons',quiz:[['What makes flamingos pink?','The shrimp and algae they eat','Pink paint','The sun'],['How do flamingos often stand?','On one leg','On their heads','On three legs'],['How do flamingos eat?','With their heads upside down','With a spoon','Only at night in trees']]},
 dolphin:{sp:'Bottlenose Dolphin',cap:'A real bottlenose dolphin surfing the wave behind a boat.',intro:['Bottlenose dolphins are mammals, so they breathe air through a blowhole on top of their heads.','Each dolphin has its own signature whistle, a bit like a name.','They live in groups called pods.','They find food with echolocation: they send out clicks and listen for the echoes.'],credit:'Photo: NASA, public domain, Wikimedia Commons',quiz:[['How do dolphins breathe?','Air through a blowhole','Water through gills','They don’t breathe'],['What is a group of dolphins called?','A pod','A flock','A herd of cows'],['How do dolphins find food?','Echolocation: clicks and echoes','They smell it from space','They ask a crab']]}};
const ITEMS={
 hat:[{id:'sunhat',name:'Sun Hat',free:1},{id:'bow',name:'Bow',free:1},{id:'crown',name:'Crown',need:['missions',3,'Finish 3 daily missions']},{id:'partyhat',name:'Party Hat',need:['levelups',3,'Level up 3 times']},{id:'flowercrown',name:'Flower Crown',need:['guide',5,'Read about 5 animals in the Field Guide']},{id:'beanie',name:'Beanie',need:['sprintBest',15,'Get 15 right in one Fact Sprint']},{id:'pirate',name:'Pirate Hat',need:['math',40,'Answer 40 math questions right']},{id:'headphones',name:'Headphones',need:['streakBest',3,'Play 3 days in a row']},{id:'cowboy',name:'Cowboy Hat',need:['rescues',3,'Rescue 3 critters']}],
 face:[{id:'round',name:'Round Glasses',free:1},{id:'heart',name:'Heart Glasses',free:1},{id:'starshades',name:'Star Shades',need:['spell',20,'Spell 20 words right']},{id:'mask',name:'Hero Mask',need:['checkup',1,'Finish the Rescue Check-up']},{id:'goggles',name:'Dive Goggles',need:['quiz',3,'Pass 3 Field Guide quizzes']}],
 neck:[{id:'bowtie',name:'Bow Tie',free:1},{id:'bandana',name:'Bandana',free:1},{id:'scarf',name:'Scarf',need:['writes',3,'Send 3 pieces to Coach Hoot']},{id:'necklace',name:'Pearl Necklace',need:['rescues',2,'Rescue 2 critters']},{id:'medal',name:'Gold Medal',need:['perfect',1,'Get every answer right in a station']},{id:'cape',name:'Hero Cape',need:['streakBest',5,'Play 5 days in a row']}],
 hold:[{id:'flower',name:'Flower',free:1},{id:'icecream',name:'Ice Cream',free:1},{id:'balloon',name:'Balloon',need:['correct',100,'Answer 100 questions right']},{id:'book',name:'Book',need:['quiz',5,'Pass 5 Field Guide quizzes']},{id:'wand',name:'Star Wand',need:['levelups',6,'Level up 6 times']},{id:'fish',name:'Fish Friend',need:['hand',2,'Write 2 pieces by hand']}],
 bg:[{id:'sunset',name:'Sunset Lagoon',free:1},{id:'day',name:'Sunny Day',free:1},{id:'night',name:'Starry Night',need:['missions',5,'Finish 5 daily missions']},{id:'rainbow',name:'Rainbow',need:['levelups',4,'Level up 4 times']},{id:'reef',name:'Coral Reef',need:['guide',12,'Read about all 12 animals']},{id:'fireworks',name:'Fireworks',need:['streakBest',7,'Play 7 days in a row']}],
 decor:[{id:'umbrella',name:'Beach Umbrella',free:1},{id:'sandcastle',name:'Sandcastle',free:1},{id:'beachball',name:'Beach Ball',need:['correct',50,'Answer 50 questions right']},{id:'surfboard',name:'Surfboard',need:['write',25,'Answer 25 writing questions right']},{id:'lighthouse',name:'Lighthouse',need:['rescues',4,'Rescue 4 critters']},{id:'treasure',name:'Treasure Chest',need:['hearts',500,'Earn 500 hearts']}]};
function statC(k){const st=S.stats||{};switch(k){case'rescues':return S.rescued.length;case'hearts':return S.hearts;case'checkup':return placedAll()?1:0;case'guide':return(S.guide||[]).length;case'quiz':return(S.quiz||[]).length;case'sprintBest':return S.best.sprint||0;case'streakBest':return Math.max(st.streakBest||0,streakNow());default:return st[k]||0}}
let SVGN=0;
const COVE_T={sunset:{sky:['#78c6db','#ffe3b9','#ffb78c'],sun:[770,120,'#fff4cf','#ffe6a0'],sea:['#43bcc4','#137c8a'],far:'#3b8a70',sand:'#f2d9a4',grass:['#93d47c','#57a953'],palm:'#1f7a55'},
 day:{sky:['#4fb3e8','#a9dcf5','#e6f7ff'],sun:[160,64,'#fffbe6','#fff1a8'],sea:['#35c6d8','#0e88a5'],far:'#4fa27f',sand:'#f7e4b5',grass:['#a2e285','#5eb659'],palm:'#1f8a58'},
 night:{sky:['#0b1233','#1e2a5e','#3b427c'],moon:[790,70],stars:1,sea:['#1b5d71','#0b3441'],far:'#1e4a44',sand:'#a8966f',grass:['#447f4d','#2a5a36'],palm:'#15432f'},
 rainbow:{sky:['#5bb6e6','#b8e2f6','#fff1f6'],sun:[880,56,'#fffbe6','#fff1a8'],rainbow:1,sea:['#39c7d7','#118aa6'],far:'#4fa27f',sand:'#f7e4b5',grass:['#a2e285','#5eb659'],palm:'#1f8a58'},
 fireworks:{sky:['#0a0f2e','#1c2358','#352f6e'],moon:[880,60],stars:1,fire:1,sea:['#1b5d71','#0b3441'],far:'#1e4a44',sand:'#a8966f',grass:['#447f4d','#2a5a36'],palm:'#15432f'},
 reef:{reef:1}};
const COVE_D={umbrella:[250,246,1],sandcastle:[640,250,.9],beachball:[470,254,.75],surfboard:[880,242,.9],lighthouse:[955,158,.72],treasure:[370,254,.85]};
const O=`stroke="${'#3d2c2e'}" stroke-width="3" stroke-linejoin="round"`;
function decorCove(id){switch(id){
 case'umbrella':return`<path d="M2 0 L-6 -86" stroke="#8a5a30" stroke-width="5" stroke-linecap="round"/><path d="M-60 -70 Q-12 -130 48 -92 Q-6 -86 -60 -70Z" fill="#ff6b57" ${O}/><path d="M-26 -89 Q-10 -114 14 -111" stroke="#fff" stroke-width="7" fill="none"/><rect x="-46" y="-8" width="62" height="10" rx="3" fill="#5ec8ff" ${O}/>`;
 case'sandcastle':return`<path d="M-44 0 V-30 H-34 V-40 H-24 V-30 H-12 V-52 H12 V-30 H24 V-40 H34 V-30 H44 V0Z" fill="#f2cf85" ${O}/><path d="M-5 -30 h10 v-10 a5 5 0 0 0 -10 0Z" fill="#c99a52"/><path d="M0 -52 V-74" stroke="#6a4429" stroke-width="3"/><path d="M0 -74 L18 -68 L0 -62Z" fill="#ff6b57"/>`;
 case'beachball':return`<g transform="translate(0 -24)"><circle r="24" fill="#fff"/><path d="M0 -24 A24 24 0 0 1 20.8 12 L0 0Z" fill="#ff5a6e"/><path d="M20.8 12 A24 24 0 0 1 -20.8 12 L0 0Z" fill="#ffd23f"/><path d="M-20.8 12 A24 24 0 0 1 0 -24 L0 0Z" fill="#4aa8ff"/><circle r="24" fill="none" ${O}/><circle r="5" fill="#fff" ${O}/></g>`;
 case'surfboard':return`<g transform="rotate(-12 0 -60)"><ellipse cx="0" cy="-60" rx="15" ry="60" fill="#4fc3f7" ${O}/><path d="M0 -116 V-4" stroke="#ff6b57" stroke-width="5"/></g>`;
 case'lighthouse':return`<path d="M18 -132 L100 -154 L100 -110Z M-18 -132 L-100 -154 L-100 -110Z" fill="#fff6c0" opacity=".5"/><path d="M-20 0 L-12 -120 H12 L20 0Z" fill="#fff" ${O}/><path d="M-18.3 -26 H18.3 L16.9 -48 H-16.9Z M-15.3 -74 H15.3 L13.9 -96 H-13.9Z" fill="#e8483a"/><rect x="-15" y="-140" width="30" height="20" rx="3" fill="#ffe58a" ${O}/><path d="M-20 -140 H20 L0 -158Z" fill="#e8483a" ${O}/>`;
 case'treasure':return`<rect x="-28" y="-30" width="56" height="30" rx="4" fill="#9a6a3a" ${O}/><path d="M-28 -30 Q0 -54 28 -30Z" fill="#b07a44" ${O}/><rect x="-28" y="-34" width="56" height="7" fill="#ffc53d" ${O}/><rect x="-6" y="-26" width="12" height="12" rx="2" fill="#ffc53d" ${O}/><g fill="#ffd23f" stroke="#b58600" stroke-width="1.5"><circle cx="-36" cy="-5" r="5.5"/><circle cx="34" cy="-5" r="5.5"/><circle cx="40" cy="-14" r="4.5"/></g>`}return''}
function palm(x,y,s,c){return`<g transform="translate(${x} ${y}) scale(${s})"><path d="M34 232 C40 192 32 152 50 110" stroke="#7d5230" stroke-width="10" fill="none" stroke-linecap="round"/><g fill="${c}"><path d="M50 110 C22 98 2 110 -10 128 C14 112 34 110 50 112Z"/><path d="M50 110 C72 90 102 94 118 110 C94 100 72 104 50 112Z"/><path d="M50 110 C42 82 58 66 78 62 C64 78 58 94 52 112Z"/><path d="M50 110 C28 82 8 80 -6 86 C18 88 34 98 48 112Z"/><path d="M50 110 C78 106 96 120 102 140 C86 124 70 116 50 114Z"/></g></g>`}
function coveSVG(bg,decor){const u='c'+(SVGN++),t=COVE_T[bg]||COVE_T.sunset;let s='';const waves=' q30 -7 60 0'+' t60 0'.repeat(21);
 if(t.reef){s=`<defs><linearGradient id="${u}w" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#5fd0dc"/><stop offset=".55" stop-color="#1f93b3"/><stop offset="1" stop-color="#0c5a7c"/></linearGradient></defs><rect width="1000" height="280" fill="url(#${u}w)"/><g fill="#fff" opacity=".12"><polygon points="120,0 190,0 330,280 240,280"/><polygon points="480,0 530,0 640,280 570,280"/><polygon points="780,0 850,0 960,280 880,280"/></g>
  <path d="M0 236 C160 222 320 234 500 228 C680 222 840 232 1000 226 V280 H0Z" fill="#f2d9a4"/>
  <g stroke-linecap="round" fill="none"><path d="M60 240 Q48 210 62 186 Q76 162 64 140" stroke="#2fa35a" stroke-width="7"/><path d="M84 240 Q96 206 82 180" stroke="#43c06b" stroke-width="6"/><path d="M930 238 Q918 204 934 176 Q948 150 936 130" stroke="#2fa35a" stroke-width="7"/></g>
  <g><path d="M150 240 C140 210 160 200 170 216 C176 196 196 200 190 222 C204 214 212 232 200 240Z" fill="#ff7aa2"/><path d="M780 240 C770 214 788 204 796 220 C804 200 824 206 816 226 C830 220 836 236 826 240Z" fill="#ff9f5a"/><circle cx="560" cy="232" r="14" fill="#b38bff"/><circle cx="578" cy="238" r="10" fill="#d7bdff"/></g>
  <g fill="#fff" opacity=".55"><circle cx="210" cy="120" r="5"/><circle cx="220" cy="92" r="3.5"/><circle cx="700" cy="140" r="6"/><circle cx="712" cy="104" r="4"/><circle cx="706" cy="76" r="2.5"/></g>
  <g fill="#ffd23f"><path d="M330 90 q14 -10 28 0 q-14 10 -28 0Z M358 90 l10 -7 v14Z"/><path d="M620 60 q12 -8 24 0 q-12 8 -24 0Z M644 60 l8 -6 v12Z" fill="#ff8f6b"/></g>`}
 else{s=`<defs><linearGradient id="${u}s" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${t.sky[0]}"/><stop offset=".58" stop-color="${t.sky[1]}"/><stop offset="1" stop-color="${t.sky[2]}"/></linearGradient><linearGradient id="${u}e" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${t.sea[0]}"/><stop offset="1" stop-color="${t.sea[1]}"/></linearGradient><linearGradient id="${u}g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${t.grass[0]}"/><stop offset="1" stop-color="${t.grass[1]}"/></linearGradient>${t.sun?`<radialGradient id="${u}n"><stop offset="0" stop-color="${t.sun[3]}"/><stop offset="1" stop-color="${t.sun[3]}" stop-opacity="0"/></radialGradient>`:''}</defs><rect width="1000" height="280" fill="url(#${u}s)"/>`;
  if(t.stars)s+=`<g fill="#fff">${Array.from({length:40},(_,i)=>`<circle cx="${(i*97)%1000}" cy="${(i*37)%130+6}" r="${i%5?1.2:2}" opacity="${.5+(i%3)*.2}" ${i%4?'':'class="twk"'}/>`).join('')}</g>`;
  if(t.rainbow)s+=`<g fill="none" stroke-width="12" opacity=".75">${['#ff5a6e','#ff9f43','#ffd23f','#54c96a','#4aa8ff','#8f6bff'].map((c,i)=>`<path d="M${210+i*12} 160 A${290-i*12} ${190-i*12} 0 0 1 ${790-i*12} 160" stroke="${c}"/>`).join('')}</g>`;
  if(t.sun)s+=`<circle cx="${t.sun[0]}" cy="${t.sun[1]}" r="100" fill="url(#${u}n)"/><circle cx="${t.sun[0]}" cy="${t.sun[1]}" r="38" fill="${t.sun[2]}"/>`;
  if(t.moon)s+=`<circle cx="${t.moon[0]}" cy="${t.moon[1]}" r="30" fill="#fff6d6"/><circle cx="${t.moon[0]+13}" cy="${t.moon[1]-8}" r="27" fill="${t.sky[0]}"/>`;
  if(t.fire)s+=[[220,70,'#ff6b8a'],[560,48,'#ffd23f'],[380,104,'#5ec8ff']].map(([x,y,c])=>`<g stroke="${c}" stroke-width="3" stroke-linecap="round" class="twk">${Array.from({length:12},(_,i)=>{const a=i*Math.PI/6;return`<path d="M${(x+Math.cos(a)*10).toFixed(0)} ${(y+Math.sin(a)*10).toFixed(0)} L${(x+Math.cos(a)*30).toFixed(0)} ${(y+Math.sin(a)*30).toFixed(0)}"/>`}).join('')}</g>`).join('');
  if(!t.moon&&!t.stars)s+=`<g class="cloudg" opacity=".9"><ellipse cx="120" cy="52" rx="62" ry="15" fill="#fff"/><ellipse cx="150" cy="42" rx="34" ry="16" fill="#fff"/></g>`;
  s+=`<path d="M0 152 C40 132 80 142 120 134 C150 124 180 138 220 132 C270 118 300 136 340 130 C380 122 420 138 470 132 C520 120 560 138 610 130 C660 122 700 140 740 134 C800 124 840 140 890 130 C940 122 970 136 1000 132 V160 H0Z" fill="${t.far}" opacity=".85"/><rect y="152" width="1000" height="70" fill="url(#${u}e)"/><g class="waves" stroke="#eafcff" stroke-width="3" stroke-linecap="round" opacity=".45" fill="none"><path d="M0 170${waves}"/><path d="M-30 190${waves}"/></g><path d="M0 212 C120 196 240 206 360 200 C480 194 620 192 760 204 C860 210 920 198 1000 202 V280 H0Z" fill="${t.sand}"/><path d="M0 224 C140 208 260 218 380 212 C520 206 640 204 780 216 C880 222 940 210 1000 214 V280 H0Z" fill="url(#${u}g)"/>${palm(40,0,1,t.palm)}${(decor||[]).includes('lighthouse')?'':palm(880,30,.8,t.palm)}`}
 (decor||[]).forEach(d=>{const p=COVE_D[d];if(p)s+=`<g transform="translate(${p[0]} ${p[1]}) scale(${p[2]})">${decorCove(d)}</g>`});
 return`<svg class="land" viewBox="0 0 1000 280" preserveAspectRatio="xMidYMid slice" aria-hidden="true">${s}</svg>`}
function coveScene(){const L=S.rescued;const cr=L.map((r,i)=>{const aq=['dolphin','turtle','otter','gator'].includes(r.id)&&S.scene.bg!=='reef',left=4+((i*29+11)%84),bottom=aq?92+(i%2)*10:6+(i%3)*20,dur=10+(i%5)*2,dx=(i%2?-1:1)*(28+(i%4)*12);return`<button class="cv-critter" data-act="pet" data-i="${i}" style="left:${left}%;bottom:${bottom}px;--dx:${dx}px;animation-duration:${dur}s" aria-label="${esc(r.name)}">${petArt({id:r.id,key:'r'+i},'md')}<span class="cv-name">${esc(r.name)}</span></button>`}).join('');
 return`<div class="scene">${coveSVG(S.scene.bg,S.scene.decor)}${cr}${L.length?'':'<p class="scene-empty">Your cove is waiting for its first rescued critter.</p>'}</div>`}
const BOOK=`<svg class="li" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5a2 2 0 0 1 2-2h13v15H6a2 2 0 0 0-2 2z" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linejoin="round"/><path d="M4 20V5M9 7h6" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/></svg>`;
const CFG={imgDir:'critters',guideName:'Field Guide',guideIcon:BOOK,guideIntro:'Explore real Florida animals. Read or listen, then take a quick quiz to earn hearts.',haveLabel:'In your cove',placeName:'cove',noPets:'Rescue a critter to start dressing it up!',dressBtnCls:'teal',curName:'hearts',quizReward:5,samplePet:{id:'owl',key:'_'},
 pets(){const L=S.rescued.map((r,i)=>({id:r.id,name:r.name,key:'r'+i}));if(S.current)L.push({id:S.current,name:CRITTERS[S.current].name,key:'cur'});return L},
 art:(id,size,cls,wear)=>spr(id,size,cls,wear),spec:SPEC,items:ITEMS,stat:statC,sceneSVG:coveSVG,decorArt:decorCove,gain:h=>gain(h)};
