function startQuickWrite(){screen='qw';const p=PROMPTS[(S.qwIdx||0)%PROMPTS.length];const hm=S.hand||'sometimes';const mode=hm==='always'?'hand':hm==='off'?'type':((S.qwIdx||0)%2===0?'hand':'type');S.qwIdx=(S.qwIdx||0)+1;save();QW={p,text:'',fb:null,rev:0,goal:qwGoal(),entry:null,busy:false,mode,hs:[],hh:430,pen:'#1b2a6b',tool:'pen',penSeen:false};renderQW()}
const splitSents=t=>t.split(/(?<=[.!?])\s+|\n+/).map(s=>s.trim()).filter(s=>s.split(/\s+/).filter(Boolean).length>=2);
function renderQW(){screen='qw';const base=RUN&&RUN.mode==='placement',hand=QW.mode==='hand';
 app.innerHTML=`<div class="qwrap">${qbar(base?'Writing Woods: Write It!':'Write It!',null)}<section class="box qw">
  <div class="qw-prompt"><span class="tag">${QW.p.kind}</span><h2>${esc(QW.p.t)}</h2><button class="iconbtn" data-act="qw-say" aria-label="Read the prompt to me">${ICON.speaker}</button></div>
  <div class="modeseg" role="group" aria-label="How do you want to write?"><button class="${hand?'':'on'}" data-act="qw-mode" data-m="type" aria-pressed="${!hand}">Type it</button><button class="${hand?'on':''}" data-act="qw-mode" data-m="hand" aria-pressed="${hand}">${ICON.pencil} Write by hand</button></div>
  <div class="goals"><span class="goal" id="g1">${QW.goal.n} or more sentences</span>${QW.goal.trans?'<span class="goal" id="g2">A transition word</span>':''}<span class="goal" id="g3">Capitals and end marks</span>${hand?'<span class="goal">Neat letters on the line</span>':''}</div>
  <div class="starters" aria-label="Sentence starters">${STARTERS[QW.p.kind].map(s=>`<button class="starter" data-act="qw-starter" data-t="${esc(s)}">${esc(s)}</button>`).join('')}</div>
  ${hand?`<div class="padbar"><div class="seg">${[['#1b2a6b','Blue pen'],['#132530','Pencil'],['#e8483a','Red pen']].map(([c,l])=>`<button class="tool ${QW.tool==='pen'&&QW.pen===c?'on':''}" data-act="hw-pen" data-c="${c}" aria-label="${l}"><i style="background:${c}"></i></button>`).join('')}<button class="tool ${QW.tool==='eraser'?'on':''}" data-act="hw-eraser" aria-label="Eraser"><svg viewBox="0 0 24 24" class="li"><path d="M4 16l8-8 8 8-4 4H8z" fill="#ffc9d2" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/><path d="M4 20h16" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg></button></div><div class="seg"><button class="tbtn" data-act="hw-undo">Undo</button><button class="tbtn" data-act="hw-clear">Clear</button><button class="tbtn" data-act="hw-more">+ More lines</button></div></div>
  <div class="paper" id="paper" style="height:${QW.hh}px"><canvas id="hw" aria-label="Handwriting paper"></canvas></div><p class="mini" style="margin:0">Write with your Apple Pencil. Skip a line between sentences if you like. Coach Hoot reads it when you send it.</p>`
  :`<textarea id="qwText" rows="7" spellcheck="false" autocorrect="off" autocomplete="off" autocapitalize="off" aria-label="Your writing" placeholder="Start writing here. Tap a sentence starter if you get stuck.">${esc(QW.text)}</textarea><div class="qw-meta"><span id="wc">0 words</span> · <span id="sc">0 sentences</span></div>`}
  <div id="coachArea">${QW.fb?fbHTML(QW.fb):''}</div>
  <div class="row">${hand?'':`<button class="btn ghost" data-act="qw-read">${ICON.speaker} Read my writing to me</button>`}${QW.fb&&QW.fb.self?'':`<button class="btn teal" data-act="qw-send">${QW.fb?'Send my fixes':'Send to Coach Hoot'}</button>`}${QW.fb?'<button class="btn" data-act="qw-done">I’m done</button>':''}${base&&!QW.fb?'<button class="linkbtn" data-act="qw-skip">Skip for now</button>':''}</div></section></div>`;
 drawAll();if(hand){hwInit()}else{const ta=$('#qwText');ta.addEventListener('input',()=>{QW.text=ta.value;qwMeta()});qwMeta()}}
function qwMeta(){if(QW.mode==='hand')return;const t=QW.text,w=(t.match(/[A-Za-z’']+/g)||[]).length,ss=splitSents(t),n=ss.length;$('#wc').textContent=w+(w===1?' word':' words');$('#sc').textContent=n+(n===1?' sentence':' sentences');
 $('#g1').classList.toggle('met',n>=QW.goal.n);const g2=$('#g2');if(g2)g2.classList.toggle('met',TRANS_RE.test(t));$('#g3').classList.toggle('met',n>0&&ss.every(s=>/^["“]?[A-Z]/.test(s))&&/[.!?]["”’]?\s*$/.test(t.trim())&&!/(^|\s)i(\s|’|')/.test(t))}
/* handwriting paper */
const HW_GAP=46,HW_TOP=58;
function hwPaper(ctx,W,H,s=1){ctx.fillStyle='#fffdf7';ctx.fillRect(0,0,W*s,H*s);ctx.strokeStyle='#b9d3ea';ctx.lineWidth=1.4*s;for(let y=HW_TOP;y<H;y+=HW_GAP){ctx.beginPath();ctx.moveTo(0,y*s);ctx.lineTo(W*s,y*s);ctx.stroke()}ctx.strokeStyle='#f3a3a8';ctx.lineWidth=1.6*s;ctx.beginPath();ctx.moveTo(48*s,0);ctx.lineTo(48*s,H*s);ctx.stroke()}
function hwInit(){const c=$('#hw');if(!c)return;const w=$('#paper'),dpr=window.devicePixelRatio||1;c.width=Math.round(w.clientWidth*dpr);c.height=Math.round(w.clientHeight*dpr);const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);hwRedraw();
 const pt=e=>{const r=c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};let cur=null;
 c.onpointerdown=e=>{if(e.pointerType==='pen')QW.penSeen=true;else if(e.pointerType==='touch'&&QW.penSeen)return;e.preventDefault();try{c.setPointerCapture(e.pointerId)}catch(_){}cur={c:QW.pen,w:QW.tool==='eraser'?22:(e.pointerType==='pen'?2.6:3),er:QW.tool==='eraser',pts:[pt(e)]};QW.hs.push(cur);hwStroke(ctx,cur,0)};
 c.onpointermove=e=>{if(!cur)return;e.preventDefault();const s=cur.pts.length-1;const evs=e.getCoalescedEvents?e.getCoalescedEvents():[e];(evs.length?evs:[e]).forEach(ev=>cur.pts.push(pt(ev)));hwStroke(ctx,cur,s)};
 c.onpointerup=c.onpointercancel=()=>{cur=null}}
function hwStroke(ctx,s,from){ctx.save();if(s.er){ctx.globalCompositeOperation='source-over';ctx.strokeStyle='#fffdf7'}else ctx.strokeStyle=s.c;ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=s.w;ctx.lineCap='round';ctx.lineJoin='round';const p=s.pts;if(p.length===1){ctx.beginPath();ctx.arc(p[0].x,p[0].y,s.w/2,0,6.283);ctx.fill()}else{ctx.beginPath();ctx.moveTo(p[Math.max(0,from)].x,p[Math.max(0,from)].y);for(let i=Math.max(1,from+1);i<p.length;i++)ctx.lineTo(p[i].x,p[i].y);ctx.stroke()}ctx.restore()}
function hwRedraw(){const c=$('#hw');if(!c)return;const ctx=c.getContext('2d'),W=c.clientWidth,H=c.clientHeight;ctx.clearRect(0,0,W,H);hwPaper(ctx,W,H);QW.hs.forEach(s=>{if(s.er){/* erase paints paper, then redraw lines under it */}hwStroke(ctx,s,0)});}
function hwBlob(){return new Promise(res=>{const src=$('#hw');const W=src.clientWidth,H=src.clientHeight,sc=Math.min(2,1400/W);const c=document.createElement('canvas');c.width=Math.round(W*sc);c.height=Math.round(H*sc);const ctx=c.getContext('2d');hwPaper(ctx,W,H,sc);ctx.setTransform(sc,0,0,sc,0,0);QW.hs.forEach(s=>hwStroke(ctx,s,0));c.toBlob(b=>res(b),'image/png')})}
function hwInk(){return QW.hs.filter(s=>!s.er).reduce((a,s)=>a+s.pts.length,0)}
const SELF=['My first word starts with a capital letter.','Every sentence ends with . ! or ?','I left spaces between my words.','My letters sit on the line and are easy to read.'];
function fbHTML(fb){if(fb.self)return`<div class="coach box"><div class="coach-h">${spr('owl','sm')}<div><b style="font-size:20px;font-family:var(--disp)">Check your own work</b><div class="muted" style="font-size:14px">Coach Hoot can’t read handwriting on this device, so be your own coach. Tap each one that’s true, or fix it first.</div></div></div><div class="selfchk">${SELF.map((t,i)=>`<button class="${fb.checks[i]?'on':''}" data-act="qw-check" data-i="${i}" aria-pressed="${!!fb.checks[i]}">${t}</button>`).join('')}</div></div>`;
 return`<div class="coach box"><div class="coach-h">${spr('owl','sm')}<div><b style="font-size:20px;font-family:var(--disp)">Coach Hoot says</b><div class="stars" aria-label="${fb.stars} of 3 stars">${[1,2,3].map(i=>`<span class="${i<=fb.stars?'on':''}">${ICON.star}</span>`).join('')}</div></div></div>
 ${fb.transcript?`<p class="readback"><b>Coach Hoot read:</b> “${esc(fb.transcript)}”</p>`:''}
 <p><b>Glow:</b> ${esc(fb.glow)}</p><p><b>Grow:</b> ${esc(fb.grow)}</p>${fb.hand?`<p><b>Handwriting tip:</b> ${esc(fb.hand)}</p>`:''}
 ${fb.fixes&&fb.fixes.length?`<div class="fixes"><b>Fix-its</b><ul>${fb.fixes.map(f=>`<li><s>${esc(f.wrong)}</s> → <b>${esc(f.right)}</b> <span class="muted">${esc(f.why||'')}</span></li>`).join('')}</ul></div>`:''}
 ${fb.example?`<p><b>Try it like this:</b> “${esc(fb.example)}”</p>`:''}</div>`}
