const LBL={correct:n=>`Get ${n} answers right`,math:n=>`Get ${n} math answers right`,read:n=>`Get ${n} reading answers right`,write:n=>`Build or fix ${n} sentences right`,missions:n=>`Finish ${n} daily missions`,daysPlayed:n=>`Play on ${n} different days`,streakBest:n=>`Play ${n} days in a row`,levelups:n=>`Level up ${n} times`,guide:n=>n>=10?'Explore all 10 dinos in the Dino Guide':`Explore ${n} dinos in the Dino Guide`,quiz:n=>n>=10?'Pass all 10 Dino Guide quizzes':`Pass ${n} Dino Guide quizzes`,perfect:n=>n===1?'Get every answer right in a station':`Get every answer right in ${n} stations`,crew:n=>`Hatch ${n} crew members`,earned:n=>`Earn ${n.toLocaleString('en-US')} stars in all`,bonus:n=>`Remember ${n} answers in bonus rounds`,blastBest:n=>`Zap ${n} meteors in one Meteor Blast`,checkup:()=>'Finish the Launch Check'};
const Fr=(id,name)=>({id,name,free:1}),Ch=(id,name,s,n,t)=>({id,name,need:[s,n,LBL[s](n)],t}),By=(id,name,cost,t)=>({id,name,cost,t});
const ITEMS={
 hat:[Fr('spacehelmet','Space Helmet'),Fr('partyhat','Party Hat'),Ch('crown','Gold Crown','missions',2),Ch('beanie','Beanie','blastBest',10),Ch('antenna','Alien Antennae','guide',5),Ch('headphones','Headphones','streakBest',3),Ch('cowboy','Cowboy Hat','math',40,1),Ch('pirate','Pirate Hat','read',40,1),Ch('wizard','Wizard Hat','correct',250,1),Ch('propeller','Propeller Cap','daysPlayed',10,1),Ch('viking','Viking Helmet','missions',14,2),Ch('tophat','Top Hat','levelups',12,2),Ch('halo','Halo','perfect',5,2),Ch('crown-silver','Silver Crown','missions',40,3),Ch('gradcap','Graduation Cap','levelups',25,3),
  By('partyhat-green','Green Party Hat',100),By('beanie-red','Red Beanie',150),By('beanie-purple','Purple Beanie',150),By('cap-red','Red Cap',200),By('cap-green','Green Cap',200),By('headphones-blue','Blue Headphones',250),By('chef','Chef Hat',350,1),By('bunnyears','Bunny Ears',450,1),By('santa','Holiday Hat',600,1),By('wizard-black','Night Wizard Hat',1200,3)],
 face:[Fr('goggles','Goggles'),Fr('round','Round Glasses'),Ch('mask','Hero Mask','checkup',1),Ch('starshades','Star Shades','levelups',3),Ch('heart','Heart Glasses','quiz',3),Ch('sunglasses','Sunglasses','daysPlayed',5),Ch('stickers','Star Stickers','bonus',10,1),Ch('glasses3d','3-D Glasses','correct',500,2),Ch('mustache','Silly Mustache','missions',25,2),Ch('monocle','Monocle','quiz',10,3),
  By('round-red','Red Glasses',100),By('round-blue','Blue Glasses',100),By('heart-purple','Purple Heart Glasses',180),By('freckles','Freckles',150),By('mask-red','Red Hero Mask',250),By('sunglasses-gold','Gold Shades',1000,3)],
 neck:[Fr('bowtie','Red Bow Tie'),Fr('scarf','Blue Scarf'),Ch('bandana','Bandana','write',10),Ch('medal','Gold Medal','perfect',1),Ch('necklace','Pearl Necklace','crew',2),Ch('jetpack','Jetpack','daysPlayed',7,1),Ch('cape','Hero Cape','streakBest',5,1),Ch('tie','Blue Tie','write',40,1),Ch('backpack','Backpack','missions',10,1),Ch('wings','Angel Wings','streakBest',14,2),Ch('medal-silver','Silver Medal','perfect',15,2),Ch('cape-purple','Royal Cape','missions',50,3),Ch('wings-gold','Golden Wings','daysPlayed',60,3),
  By('bowtie-green','Green Bow Tie',100),By('bowtie-gold','Gold Bow Tie',180),By('scarf-red','Red Scarf',180),By('bandana-blue','Blue Bandana',150),By('bell','Bell Collar',300,1),By('backpack-teal','Teal Backpack',400,1),By('cape-black','Midnight Cape',800,2)],
 hold:[Fr('balloon','Red Balloon'),Fr('icecream','Ice Cream'),Ch('toyrocket','Toy Rocket','missions',5),Ch('telescope','Telescope','guide',10),Ch('wand','Star Wand','levelups',5),Ch('flower','Space Flower','correct',75),Ch('soccer','Soccer Ball','math',100,1),Ch('magnifier','Magnifying Glass','quiz',10,1),Ch('trophy','Trophy','perfect',25,2),Ch('kite','Kite','daysPlayed',30,2),Ch('lantern','Glowing Lantern','streakBest',21,3),
  By('balloon-blue','Blue Balloon',80),By('balloon-green','Green Balloon',80),By('balloon-gold','Gold Balloon',150),By('lollipop','Lollipop',180),By('icecream-green','Mint Ice Cream',200),By('pencil','Big Pencil',250),By('umbrella-blue','Umbrella',350,1),By('guitar','Guitar',800,2)],
 bg:[Fr('nebula','Purple Nebula'),Fr('bluespace','Blue Space'),Ch('moonbase','Moon Base','missions',3),Ch('mars','Mars','crew',3),Ch('saturn','Saturn','daysPlayed',7),Ch('aurora','Space Lights','quiz',5,1),Ch('comet','Rainbow Comet','streakBest',7,1),Ch('jupiter','Jupiter','correct',400,1),Ch('spiral','Spiral Galaxy','levelups',10,2),Ch('sunflare','Solar Flare','missions',25,2),Ch('blackhole','Black Hole','daysPlayed',45,3),By('candyplanet','Candy Planet',1500,3)],
 decor:[Fr('rocketship','Rocket Ship'),Fr('flag','Flag'),Ch('ufo','UFO','correct',40),Ch('crystals','Space Crystals','guide',6),Ch('satellite','Satellite','read',50),Ch('rover','Moon Rover','daysPlayed',5),Ch('alien','Alien Friend','bonus',20,1),Ch('robot','Robot Pal','math',150,1),Ch('station','Space Station','crew',4,1),Ch('tent','Space Tent','streakBest',10,2),Ch('dish','Radio Dish','missions',20,2),Ch('alienplant','Alien Plant','earned',400,1),Ch('meteor','Shooting Star','daysPlayed',40,3)]};
function statD(k){const st=S.stats||{};switch(k){case'crew':return S.crew.length;case'checkup':return placedAll()?1:0;case'guide':return(S.guide||[]).length;case'quiz':return(S.quiz||[]).length;case'blastBest':return S.best.blast||0;case'streakBest':return Math.max(st.streakBest||0,streakNow());case'earned':return Math.max(st.earned||0,S.stars);default:return st[k]||0}}
/* trend packs */
const PK=(p,list)=>list.map(it=>(it.p=p,it));
[['hat',PK('Gamer',[Ch('gamerset','Gamer Headset','math',60),By('gamerset-red','Red Gamer Headset',400,1)])],
 ['hat',PK('Ninja',[Ch('hunterband','Ninja Headband','streakBest',4),By('hunterband-red','Red Ninja Headband',250),By('hunterband-black','Shadow Ninja Headband',250)])],
 ['hat',PK('Speed & Robots',[Ch('racehelmet','Race Helmet','blastBest',15,1),Ch('robothelm','Robot Helmet','crew',6,2),By('racehelmet-blue','Blue Race Helmet',500,1),By('racehelmet-gold','Gold Race Helmet',1100,3)])],
 ['face',PK('Gamer',[Ch('pixelshades','Pixel Shades','correct',150,1)])],
 ['face',PK('Ninja',[Ch('ninjamask','Ninja Mask','perfect',3),By('ninjamask-red','Red Ninja Mask',250)])],
 ['neck',PK('Gamer',[Ch('hoodie','Cozy Hoodie','daysPlayed',8),By('hoodie-green','Green Hoodie',300),By('hoodie-red','Red Hoodie',300)])],
 ['neck',PK('Rock Star',[Ch('stagejacket-black','Rock Star Jacket','missions',12,1),By('stagejacket-gold','Gold Rock Jacket',900,3)])],
 ['hold',PK('Gamer',[Ch('controller','Game Controller','missions',6),Ch('pixelsword','Pixel Sword','blastBest',20,2),By('controller-red','Red Controller',200),By('pixelsword-purple','Purple Pixel Sword',900,2)])],
 ['hold',PK('Ninja',[Ch('moonblade','Glow Sword','levelups',8,1),By('moonblade-green','Green Glow Sword',700,2),By('moonblade-red','Red Glow Sword',700,2)])],
 ['hold',PK('Speed & Robots',[Ch('truck','Monster Truck','math',80,1),Ch('skateboard','Skateboard','daysPlayed',15,1),By('truck-blue','Blue Monster Truck',300),By('skateboard-orange','Orange Skateboard',250)])],
 ['hold',PK('Toy Box',[Ch('spinner','Fidget Spinner','read',60),Ch('popper','Pop-It Fidget','correct',120),By('slime','Glow Slime',180),By('slime-purple','Purple Slime',180),By('spinner-gold','Gold Spinner',400,1),By('mic','Rock Star Mic',400,1)])],
 ['bg',PK('Gamer',[Ch('arcade','Arcade Galaxy','missions',20,2)])],
 ['decor',PK('Gamer',[Ch('arcademachine','Arcade Machine','correct',300,1)])],
 ['decor',PK('Speed & Robots',[By('ramp','Skate Ramp',500,1)])]
].forEach(([c,l])=>ITEMS[c].push(...l));
