const LBL={correct:n=>`Answer ${n} questions right`,math:n=>`Answer ${n} math questions right`,spell:n=>`Get ${n} spelling answers right`,write:n=>`Answer ${n} writing questions right`,missions:n=>`Finish ${n} daily missions`,daysPlayed:n=>`Play on ${n} different days`,streakBest:n=>`Play ${n} days in a row`,levelups:n=>`Level up ${n} times`,guide:n=>n>=12?'Read about all 12 animals in the Field Guide':`Read about ${n} animals in the Field Guide`,quiz:n=>n>=12?'Pass all 12 Field Guide quizzes':`Pass ${n} Field Guide quizzes`,perfect:n=>n===1?'Get every answer right in a station':`Get every answer right in ${n} stations`,rescues:n=>`Rescue ${n} critters`,earned:n=>`Earn ${n.toLocaleString('en-US')} hearts in all`,writes:n=>`Send ${n} pieces to Coach Hoot`,hand:n=>`Write ${n} pieces by hand`,bonus:n=>`Remember ${n} answers in bonus rounds`,sprintBest:n=>`Get ${n} right in one Fact Sprint`,checkup:()=>'Finish the Rescue Check-up',chapters:n=>`Log ${n} chapters in Book Club`,bookart:n=>`Draw or write ${n} Book Club projects`,books:n=>n===1?'Finish a whole book in Book Club':`Finish ${n} books in Book Club`};
const Fr=(id,name)=>({id,name,free:1}),Ch=(id,name,s,n,t)=>({id,name,need:[s,n,LBL[s](n)],t}),By=(id,name,cost,t)=>({id,name,cost,t});
const ITEMS={
 hat:[Fr('sunhat','Sun Hat'),Fr('bow','Pink Bow'),Ch('crown','Gold Crown','missions',3),Ch('partyhat','Party Hat','levelups',3),Ch('flowercrown','Flower Crown','guide',5),Ch('beanie','Teal Beanie','sprintBest',15),Ch('headphones','Headphones','streakBest',3),Ch('cowboy','Cowboy Hat','rescues',3),Ch('pirate','Pirate Hat','math',60,1),Ch('wizard','Wizard Hat','correct',300,1),Ch('bunnyears','Bunny Ears','chapters',5,1),Ch('tophat','Top Hat','missions',14,1),Ch('halo','Halo','perfect',5,2),Ch('gradcap','Graduation Cap','levelups',15,2),Ch('viking','Viking Helmet','math',300,2),Ch('tiara','Tiara','daysPlayed',30,2),Ch('crown-silver','Silver Crown','missions',40,3),Ch('crown-rose','Rose Gold Crown','streakBest',30,3),
  By('bow-blue','Blue Bow',120),By('bow-purple','Purple Bow',120),By('beanie-pink','Pink Beanie',180),By('beanie-orange','Orange Beanie',180),By('cap-red','Red Cap',220),By('cap-blue','Blue Cap',220),By('headphones-purple','Purple Headphones',300),By('chef','Chef Hat',400,1),By('santa','Holiday Hat',600,1),By('propeller','Propeller Cap',900,2),By('wizard-black','Night Wizard Hat',1500,3)],
 face:[Fr('round','Round Glasses'),Fr('heart','Heart Glasses'),Ch('mask','Hero Mask','checkup',1),Ch('starshades','Star Shades','spell',25),Ch('goggles','Dive Goggles','quiz',3),Ch('sunglasses','Sunglasses','daysPlayed',5),Ch('stickers','Star Stickers','bonus',15,1),Ch('monocle','Monocle','write',120,1),Ch('glasses3d','3-D Glasses','correct',600,2),Ch('mustache','Silly Mustache','missions',30,2),Ch('heart-gold','Gold Heart Glasses','quiz',12,3),
  By('round-red','Red Glasses',120),By('round-purple','Purple Glasses',120),By('heart-blue','Blue Heart Glasses',200),By('freckles','Freckles',150),By('mask-red','Red Hero Mask',300),By('sunglasses-pink','Pink Sunglasses',350,1),By('sunglasses-gold','Gold Shades',1200,3)],
 neck:[Fr('bowtie','Red Bow Tie'),Fr('bandana','Red Bandana'),Ch('scarf','Blue Scarf','writes',3),Ch('necklace','Pearl Necklace','rescues',2),Ch('medal','Gold Medal','perfect',1),Ch('cape','Hero Cape','streakBest',5),Ch('tie','Blue Tie','writes',10,1),Ch('lei','Flower Lei','guide',12,1),Ch('backpack','Backpack','daysPlayed',10,1),Ch('bell','Bell Collar','spell',150,1),Ch('wings','Angel Wings','streakBest',14,2),Ch('medal-silver','Silver Medal','perfect',15,2),Ch('cape-purple','Royal Cape','missions',60,3),Ch('wings-gold','Golden Wings','daysPlayed',75,3),
  By('bowtie-blue','Blue Bow Tie',120),By('bowtie-gold','Gold Bow Tie',200),By('bandana-blue','Blue Bandana',150),By('scarf-green','Green Scarf',220),By('scarf-pink','Pink Scarf',220),By('tie-purple','Purple Tie',300),By('backpack-teal','Teal Backpack',450,1),By('cape-black','Midnight Cape',900,2)],
 hold:[Fr('flower','Flower'),Fr('icecream','Ice Cream'),Ch('balloon','Red Balloon','correct',100),Ch('book','Book','quiz',5),Ch('fish','Fish Friend','hand',2),Ch('wand','Star Wand','levelups',6),Ch('pencil','Big Pencil','writes',25,1),Ch('magnifier','Magnifying Glass','quiz',12,1),Ch('paintbrush','Paintbrush','bookart',5,1),Ch('trophy','Trophy','perfect',30,2),Ch('kite','Kite','daysPlayed',40,2),Ch('lantern','Glowing Lantern','streakBest',21,3),Ch('book-gold','Golden Book','books',3,3),
  By('balloon-blue','Blue Balloon',100),By('balloon-gold','Gold Balloon',150),By('balloon-purple','Purple Balloon',150),By('flower-gold','Sunflower',180),By('lollipop','Lollipop',200),By('icecream-green','Mint Ice Cream',220),By('soccer','Soccer Ball',300),By('umbrella-red','Red Umbrella',400,1),By('umbrella-blue','Blue Umbrella',400,1),By('guitar','Guitar',900,2)],
 bg:[Fr('sunset','Sunset Lagoon'),Fr('day','Sunny Day'),Ch('sunrise','Sunrise','daysPlayed',5),Ch('night','Starry Night','missions',5),Ch('rainbow','Rainbow','levelups',4),Ch('fireworks','Fireworks','streakBest',7,1),Ch('reef','Coral Reef','guide',12,1),Ch('mangrove','Mangrove Swamp','correct',400,1),Ch('storm','Thunderstorm','math',200,2),Ch('glow','Glowing Beach','quiz',12,2),Ch('snowday','Snow Day','missions',30,2),By('candy','Candy Land',2000,3)],
 decor:[Fr('umbrella','Beach Umbrella'),Fr('sandcastle','Sandcastle'),Ch('chair','Beach Chair','daysPlayed',5),Ch('beachball','Beach Ball','correct',50),Ch('shells','Seashells','guide',8),Ch('treasure','Treasure Chest','earned',500),Ch('surfboard','Surfboard','write',25,1),Ch('lighthouse','Lighthouse','rescues',4,1),Ch('pelican','Pelican on a Post','rescues',6,1),Ch('flamingofloat','Flamingo Float','bonus',30,1),Ch('tiki','Tiki Torches','streakBest',10,2),Ch('boat','Sailboat','missions',20,2),Ch('kayak','Kayak','correct',800,2),Ch('bonfire','Beach Bonfire','daysPlayed',30,3)]};
function statC(k){const st=S.stats||{};switch(k){case'rescues':return S.rescued.length;case'checkup':return placedAll()?1:0;case'guide':return(S.guide||[]).length;case'quiz':return(S.quiz||[]).length;case'sprintBest':return S.best.sprint||0;case'streakBest':return Math.max(st.streakBest||0,streakNow());case'earned':return Math.max(st.earned||0,S.hearts);case'chapters':return(S.books||[]).reduce((a,b)=>a+(b.log||[]).length,0);case'bookart':return(S.books||[]).reduce((a,b)=>a+(b.log||[]).filter(l=>l.art||l.story).length,0);case'books':return(S.books||[]).filter(b=>b.done).length;default:return st[k]||0}}
/* trend packs */
const PK=(p,list)=>list.map(it=>(it.p=p,it));
[['hat',PK('Pop Idol',[Ch('beret','Stage Beret','streakBest',4),Ch('starclips','Star Clips','spell',40),By('beret-purple','Purple Stage Beret',250),By('starclips-pink','Pink Star Clips',180)])],
 ['hat',PK('Glow Hunter',[Ch('hunterband','Hunter Headband','quiz',6,1),By('hunterband-red','Crimson Headband',500,1)])],
 ['hat',PK('Trend Shop',[Ch('clawclip','Claw Clip','writes',5),Ch('butterfly','Butterfly Clips','bonus',8),Ch('catphones','Cat-Ear Headphones','daysPlayed',20,2),By('scrunchie','Scrunchie Bun',160),By('clawclip-teal','Teal Claw Clip',160),By('butterfly-pink','Pink Butterfly Clips',200),By('catphones-cyan','Glow Cat-Ear Headphones',1100,3)])],
 ['hat',PK('Gamer',[Ch('gamerset','Gamer Headset','math',150,1),By('gamerset-purple','Purple Gamer Headset',450,1)])],
 ['face',PK('Pop Idol',[Ch('idolmic','Headset Mic','writes',8,1),Ch('stargems','Face Gems','perfect',3),By('idolmic-pink','Pink Headset Mic',300)])],
 ['face',PK('Trend Shop',[Fr('heartblush','Heart Blush'),By('stargems-gold','Gold Face Gems',260)])],
 ['face',PK('Gamer',[Ch('pixelshades','Pixel Shades','sprintBest',25,1)])],
 ['neck',PK('Pop Idol',[Ch('stagejacket','Sparkle Stage Jacket','missions',12,1),By('stagejacket-black','Midnight Stage Jacket',700,2),By('stagejacket-pink','Pink Stage Jacket',700,2),Ch('stagejacket-gold','Gold Encore Jacket','streakBest',25,3)])],
 ['neck',PK('Glow Hunter',[Ch('moontag','Moon Charm','guide',10),Ch('huntercoat','Hunter Coat','levelups',10,2),By('huntercoat-purple','Royal Hunter Coat',1000,3)])],
 ['neck',PK('Trend Shop',[Ch('crossbody','Mini Crossbody Bag','daysPlayed',8),By('crossbody-purple','Purple Crossbody Bag',260)])],
 ['neck',PK('Gamer',[By('hoodie','Cozy Hoodie',350,1),By('hoodie-purple','Purple Hoodie',350,1)])],
 ['hold',PK('Pop Idol',[Ch('mic','Gold Microphone','write',60,1),Ch('lightstick','Light Stick','missions',8),By('lightstick-cyan','Blue Light Stick',220),By('mic-pink','Pink Microphone',300)])],
 ['hold',PK('Glow Hunter',[Ch('moonblade','Glow Blade','perfect',10,2),By('moonblade-pink','Pink Glow Blade',800,2),Ch('moonblade-purple','Spirit Glow Blade','quiz',12,3)])],
 ['hold',PK('Trend Shop',[Ch('bubbletea','Taro Bubble Tea','correct',150),Ch('bracelets','Friendship Bracelets','writes',15,1),Ch('popper','Pop-It Fidget','spell',80),By('bubbletea-matcha','Matcha Bubble Tea',150),By('bubbletea-berry','Strawberry Bubble Tea',150),By('tumbler','Big Tumbler',220),By('tumbler-lilac','Lilac Tumbler',220),By('slime','Glow Slime',200),By('slime-pink','Pink Slime',200),By('phone','Sparkle Phone',400,1)])],
 ['hold',PK('Gamer',[Ch('controller','Game Controller','sprintBest',20),By('controller-teal','Teal Controller',250)])],
 ['bg',PK('Pop Idol',[Ch('stage','Concert Stage','missions',15,2)])],
 ['bg',PK('Trend Shop',[By('city','Neon City Night',1200,2)])],
 ['decor',PK('Pop Idol',[Ch('speakers','Stage Speakers','streakBest',6,1),By('discoball','Disco Ball',600,1)])]
].forEach(([c,l])=>ITEMS[c].push(...l));
