const REAL={
 rex:{sp:'Tyrannosaurus rex',say:'Tyrannosaurus rex',cap:'This is a real T. rex fossil skeleton at the Carnegie Museum of Natural History in Pittsburgh.',intro:['Tyrannosaurus rex lived about 66 million years ago in North America.','It was about as long as a school bus, and its teeth were as long as bananas!','It walked on two strong legs and had tiny arms with just two fingers.','Scientists learn about T. rex by studying fossil bones like these.'],credit:'Photo: ScottRobertAnselmo, CC BY-SA 3.0, Wikimedia Commons'},
 bronto:{sp:'Brontosaurus',say:'Brontosaurus',cap:'This is a real Brontosaurus skeleton at the Yale Peabody Museum in Connecticut.',intro:['Brontosaurus was a giant plant-eater with a very long neck and a long tail.','Its name means thunder lizard!','It was longer than a school bus and weighed about as much as three elephants.','It lived about 150 million years ago.'],credit:'Photo: Matthew Bellemare, CC BY-SA 2.0, Wikimedia Commons'},
 zap:{sp:'Velociraptor',say:'Velociraptor',cap:'This is a Velociraptor skeleton. Look at its long tail and sharp claws!',intro:['Velociraptor was about the size of a turkey, much smaller than in the movies!','It had feathers, a long stiff tail, and a big curved claw on each foot.','It lived about 75 million years ago in the deserts of Mongolia.'],credit:'Photo: Eduard Solà Vázquez, CC BY 3.0, Wikimedia Commons'},
 nova:{sp:'Stegosaurus',say:'Stegosaurus',cap:'This is Sophie, a real Stegosaurus skeleton at the Natural History Museum in London.',intro:['Stegosaurus had big bony plates along its back and sharp spikes on its tail.','It ate plants and lived about 150 million years ago.','Its head was very small for such a big body.'],credit:'Photo: Susannah Maidment et al. and the Natural History Museum, London, CC BY 4.0, Wikimedia Commons'},
 pinky:{sp:'Triceratops',say:'Triceratops',cap:'This is a real Triceratops skeleton at the Natural History Museum of Los Angeles.',intro:['Triceratops had three horns and a giant bony frill around its neck.','Its name means three-horned face.','It ate plants and lived about 66 million years ago, at the same time as T. rex.'],credit:'Photo: Allie Caulfield, edited by MathKnight, CC BY-SA 3.0, Wikimedia Commons'},
 sunny:{sp:'Ankylosaurus',say:'Ankylosaurus',cap:'This is a model of a real Ankylosaurus head at the Museum of the Rockies in Montana. See the bumpy armor?',intro:['Ankylosaurus was covered in bony armor, like a walking tank.','It had a heavy club at the end of its tail to protect itself.','It ate plants and lived about 66 million years ago.'],credit:'Photo: Tim Evanson, CC BY-SA 2.0, Wikimedia Commons'},
 shelly:{sp:'Archelon',say:'Archelon',cap:'This is a fossil of Archelon, a giant sea turtle from long ago.',intro:['Archelon was a giant sea turtle that swam in the ocean while dinosaurs walked on land.','It was about as long as a car!','It lived about 75 million years ago.'],credit:'Photo: Mike Beauregard, CC BY 2.0, Wikimedia Commons'},
 chomp:{sp:'Deinosuchus',say:'Deinosuchus',cap:'This is a model of a Deinosuchus skull at Big Bend National Park in Texas. Look at those teeth!',intro:['Deinosuchus was a giant relative of alligators and crocodiles.','It could grow as long as a school bus, and it may have even eaten dinosaurs!','It lived about 80 million years ago near rivers and the ocean.'],credit:'Photo: Jonathan Cutrer, edited by MathKnight, CC BY 4.0, Wikimedia Commons'},
 ziggy:{sp:'Pteranodon',say:'Pteranodon',cap:'This is a life-size Pteranodon model made from fossils, at the American Museum of Natural History in New York.',intro:['Pteranodon was a flying reptile, not a dinosaur.','Its wings stretched wider than a car is long!','It had no teeth and probably caught fish over the ocean.','It lived about 85 million years ago.'],credit:'Photo: Matt Martyniuk, CC BY 3.0, Wikimedia Commons'},
 sparky:{sp:'Spinosaurus',say:'Spinosaurus',cap:'This is a Spinosaurus skeleton model at the Field Museum in Chicago, shown swimming.',intro:['Spinosaurus had a giant sail on its back and a long snout like a crocodile.','It spent lots of time in rivers and ate fish.','It was even longer than T. rex, and it lived about 95 million years ago in North Africa.'],credit:'Photo: 3blindMies, CC BY-SA 4.0, Wikimedia Commons'}};
const realImg=(id,cls='')=>`<img class="realpic ${cls}" src="dino/${id}.jpg" alt="${esc(REAL[id].cap)}" onerror="this.style.display='none'">`;
function openLearn(id,who){const r=REAL[id],c=CREW[id];if(!r)return;const m=$('#modal');
 m.innerHTML=`<div class="box learn" role="dialog" aria-modal="true" aria-label="${esc(r.sp)}"><div class="learn-h">${crit(id,'md')}<div><div class="tag">Real dino facts</div><h2>${esc(r.sp)}</h2></div><button class="iconbtn" id="lClose" aria-label="Close">${ICON.x}</button></div>${realImg(id,'big')}<p class="cap">${esc(r.cap)}</p><ul class="facts">${r.intro.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><div class="row"><button class="btn cyan sm" id="lSay">${ICON.speaker} Hear it again</button><button class="btn ghost sm" id="lDone">Back</button></div><p class="credit">${esc(r.credit)}</p></div>`;
 m.hidden=false;const speak=()=>say([who?`Hi! I'm ${who}!`:'',400,`This is ${r.say}.`,500,r.cap,700,...r.intro.flatMap(t=>[t,450])]);speak();
 const close=()=>{m.hidden=true;hush()};$('#lClose').onclick=close;$('#lDone').onclick=close;$('#lSay').onclick=speak;m.onclick=e=>{if(e.target===m)close()}}
function renderHatch(){screen='hatch';const have=new Set(S.crew.map(c=>c.id));let pool=CIDS.filter(i=>!have.has(i));if(!pool.length)pool=CIDS.slice();const id=S.hatching||(S.hatching=pick(pool));save();
 app.innerHTML=`${topbar()}<div class="box center-card"><div id="hatchArt">${eggSVG(S.egg,150,'crack')}</div><h1 id="hatchH">Your egg is hatching!</h1><div id="hatchRest"></div></div>`;wireGate();sfx.boom();say('Your egg is hatching!');
 setTimeout(()=>{const c=CREW[id],r=REAL[id];$('#hatchArt').innerHTML=`<div class="glow">${crit(id,'xl','bob')}</div>`;$('#hatchH').textContent=`Meet ${c.name}!`;sfx.win();burst();setTimeout(()=>burst(innerWidth*.3,innerHeight*.4),250);
  $('#hatchRest').innerHTML=`<p style="margin:0 0 12px;font-size:22px">${c.name} is a <b>${esc(r.sp)}</b> and your new <b>${c.role}</b>.</p>
  <div class="realcard"><div class="realtag">Real ${esc(r.sp)}</div>${realImg(id)}<p class="cap">${esc(r.cap)}</p></div>
  <div class="row center" style="margin-top:12px"><button class="btn ghost sm" data-act="learn" data-id="${id}">Learn more about ${esc(r.sp)}</button></div>
  <p style="margin:16px 0 6px">Want a different name?</p><input id="cn" class="nameinput" maxlength="14" value="${esc(c.name)}" autocomplete="off"><div style="margin-top:14px"><button class="btn cyan" data-act="hatch-done">Welcome aboard! ${ICON.arrow}</button></div>`;
  say([`Meet ${c.name}!`,400,`${c.name} is a ${r.say}, and your new ${c.role}.`,700,r.cap,600,r.intro[0]])},1500)}
