import {open,shot,SPEECH_MOCK} from './lib.mjs';import {placed} from './setup.mjs';
for(const f of ['critter-cove.html','dino-star-patrol.html'])for(const vp of ['ipad','ipadair','iphone']){const p=await open(f,vp,{init:SPEECH_MOCK});await placed(p);
 const res=await p.evaluate(()=>{S.bought=allItems().filter(i=>i.cost).map(i=>i.id);DU.tab='decor';const out=[];for(const it of CFG.items.decor){S.scene.decor=[it.id];renderDress();const v=document.querySelector('.ssview');const vr=v.getBoundingClientRect();const gs=[...v.querySelectorAll('svg g[transform^="translate"]')];const g=gs[gs.length-1];const r=g.getBoundingClientRect();const a=Math.max(0,Math.min(r.right,vr.right)-Math.max(r.left,vr.left))*Math.max(0,Math.min(r.bottom,vr.bottom)-Math.max(r.top,vr.top))/(r.width*r.height||1);if(a<.85)out.push(it.id+':'+Math.round(a*100)+'%')}return out});
 console.log(f.split('-')[0],vp,'decor <85% visible in strip:',res.length?res.join(' '):'none');await p.b.close()}
{const p=await open('dino-star-patrol.html','iphone',{init:SPEECH_MOCK});await placed(p);await p.evaluate(()=>{S.placement={math:false,read:false,at:null};save();render()});await shot(p,'fix-dino-iphone-home-speaker',false);
 await p.evaluate(()=>openLearn('rex'));await p.waitForTimeout(300);await shot(p,'fix-dino-iphone-learn-rex',false);
 await p.evaluate(()=>{document.querySelector('#modal').hidden=true;startCheck('math')});await p.waitForTimeout(300);await p.click('[data-act="idk"]');await p.waitForTimeout(200);console.log('dino idk fb:',await p.evaluate(()=>document.querySelector('#fb').innerText.replace(/\n/g,' | ')));await p.b.close()}
{const p=await open('critter-cove.html','iphone',{init:SPEECH_MOCK});await placed(p);await p.evaluate(()=>{RUN={used:new Set()};let q;for(let i=0;i<50;i++){q=mk('spell',3);if(q.type==='spell')break}RUN={mode:'practice',station:'spell',title:'Spelling Splash',planner:{pos:()=>1,total:8,next:()=>null},results:[],used:new Set(),earned:0,ups:[]};RUN.q=q;RUN.tries=0;RUN.locked=false;A={buf:'',fr:{w:'',n:'',d:''},focus:'n'};renderQ()});await p.waitForTimeout(200);await shot(p,'fix-critter-iphone-spelling',false);
 const rep=await p.evaluate(()=>{let reps=0,tot=0;for(let t=0;t<20;t++){startCheck('math');let prev=null;let guard=0;while(RUN&&RUN.q&&screen==='q'&&guard++<60){tot++;const k=RUN.q.prompt.replace(/<[^>]+>/g,'')+'|'+(RUN.q.fig||'');if(k===prev)reps++;prev=k;RUN.locked=false;RUN.planner.result(Math.random()<.7);nextQ()}}return{reps,tot}});console.log('critter placement consecutive identical:',JSON.stringify(rep));
 console.log(p.errs);await p.b.close()}
